<?php
	define('DEFAULT_TIMEZONE' , '');
	define('DEVELOPMENT_MODE' , true);
	define('ROOT', str_replace('\\', '/', dirname(__FILE__)) . '/');
	define('ROOT_DIR_NAME' , basename(ROOT)); 
	define('SITE_NAME' , "boteco");
	$site_addr = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['SCRIPT_NAME']);
	$site_addr = rtrim($site_addr,"/\\") . "/"; 
	define('SITE_ADDR' , $site_addr);
	define('APP_ID',"de9f1c710ecdb260230b760e9bb22c56");
	define('META_THEME_COLOR',"#000000"); 
	define('IMG_DIR',  "assets/images/");
	define('SITE_FAVICON',IMG_DIR . "favicon.png");
	define('SITE_LOGO',IMG_DIR . "logo.png");
	define('CSS_DIR',SITE_ADDR . "assets/css/");
	define('JS_DIR',SITE_ADDR . "assets/js/");
	define('APP_DIR',"app/");
	define('SYSTEM_DIR','system/');
	define('HELPERS_DIR','helpers/');
	define('LIBS_DIR','libs/');
	define('LANGS_DIR','languages/');
	define('MODELS_DIR',APP_DIR . "models/");
	define('CONTROLLERS_DIR',APP_DIR . 'controllers/');
	define('VIEWS_DIR',APP_DIR . 'views/');
	define('LAYOUTS_DIR',VIEWS_DIR . 'layouts/');
	define('PAGES_DIR',VIEWS_DIR . 'partials/');
	define('AUDIT_LOGS_DIR', 'logs/');
	define('UPLOAD_DIR', 'uploads/');
	define('UPLOAD_FILE_DIR',UPLOAD_DIR . 'files/');
	define('UPLOAD_IMG_DIR', UPLOAD_DIR . 'photos/');
	define('MAX_UPLOAD_FILESIZE',trim(ini_get('upload_max_filesize')));
	define('HOME_PAGE','Home');
	define("DEFAULT_PAGE","index");
	define("DEFAULT_PAGE_ACTION","index");
	define('DEFAULT_LAYOUT',LAYOUTS_DIR . 'main_layout.php');
	define("DEFAULT_LANGUAGE","portuguese");
	define('META_AUTHOR','');
	define('META_DESCRIPTION','');
	define('META_KEYWORDS','');
	define('META_VIEWPORT','width=device-width, initial-scale=1.0');
	define('PAGE_CHARSET','UTF-8');
	define('USE_SMTP',false);
	define('SMTP_USERNAME','');
	define('SMTP_PASSWORD','');
	define('SMTP_HOST','');
	define('SMTP_PORT','');
	define('DEFAULT_EMAIL','');
	define('DEFAULT_EMAIL_ACCOUNT_NAME','');
	define('DB_HOST','localhost');
	define('DB_USERNAME','vinicius');
	define('DB_PASSWORD','123');
	define('DB_NAME','meuboteco');
	define('DB_TYPE','mysql');
	define('DB_PORT','');
	define('DB_CHARSET','utf8');
	define('MAX_RECORD_COUNT', 20);
	define('ORDER_TYPE','DESC');
	define('USER_ID',(isset($_SESSION[APP_ID.'user_data']) ? $_SESSION[APP_ID.'user_data']['id'] : null ));
	define('USER_NAME',(isset($_SESSION[APP_ID.'user_data']) ? $_SESSION[APP_ID.'user_data']['usuario'] : null ));
	define('USER_EMAIL',(isset($_SESSION[APP_ID.'user_data']) ? $_SESSION[APP_ID.'user_data']['email'] : null ));